# Generated by Django 6.1 on 2026-08-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='contact_con_created_fddb83_idx'), models.Index(fields=['email'], name='contact_con_email_233940_idx'), models.Index(fields=['is_read'], name='contact_con_is_read_9a011e_idx')],
            },
        ),
    ]
